name: transfer

channels:
  - conda-forge

dependencies:
  - python=3.8
  - requests=2.23.0
  - Flask
  - jsonpickle
  - google-api-python-client
  - google-auth-httplib2
  - google-auth-oauthlib
  - importlib_resources=3.0.0
